---
- name: Crea VM desde una plantilla
  connection: local
  hosts: localhost
  gather_facts: no
  vars_files:
    - vcenter_vars.yml

  tasks:

  - name: Clonar la plantilla
    vmware_guest:
#      hostname: "{{ vcenter_ip }}"
#      username: "{{ vcenter_username }}"
#      password: "{{ vcenter_password }}"
      validate_certs: False
      name: "{{ vm_name }}"
      template: "{{ plantilla }}"
      datacenter: "{{ datacenter_name }}"
      folder: prueba 
      state: poweredon
      cluster: "{{ cluster_name }}"
      wait_for_ip_address: yes
    register: Salida

  - debug: var=Salida
