---
- name: Remove virtual machine
  connection: local
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  tasks:

    - name: Elimina "{{ vm_name }}"
      vmware_guest:
#        hostname: "{{ vcenter_ip }}"
#        username: "{{ vcenter_username }}"
#        password: "{{ vcenter_password }}"
        validate_certs: no
        cluster: "{{ cluster_name }}"
        name: "{{ vm_name }}"
        state: absent
        force: yes
      delegate_to: localhost
      register: facts
